### ISSUE TITLE
Multiple CurrencyCloud accounts and threads 

### ISSUE THREAD

**Issue by kamen-hursev** [CurrencyCloud/currencycloud-ruby#3]
We are currently using Currency Cloud Api v1 and plan to move to v2. We have a use case like this:
- User has more than one pair of `login_id`, `api_key` (each pair is for a different broker).
- User needs [detailed rates](https://connect.currencycloud.com/documentation/api-docs/get-rates-detailed) for a currency pair from each of the brokers.
- User selects the best rate and books is.

In order to speed things up we make each request for rates in a separate thread. Looking at your example of usage, we'll need something like:

```
broker_accounts = { 'login_id1' => 'key1', 'login_id2' => 'key2' }
threads = []
broker_accounts.each do |login_id, api_key|
  threads << Thread.new do
    CurrencyCloud.login_id = login_id
    CurrencyCloud.api_key = api_key
    result = CurrencyCloud::Rate.detailed(params)
    process_in_some_way(result)
  end
end 
threads.each(&:join)
```

However this will not work, because of a concurrency issue it is possible that threads overwrite each other's `login_id` and `api_key`.

I see this gem is not yet completed, but **do you plan to implement** functionality where instead of setting `login_id` and `api_key` on the module we can create instances of some class that contains the credentials?

Something like:

```
...
threads << Thread.new do
  client = CurrencyCloud::Client.new(login_id, api_key)
  result = client.rate.detailed(params)
  process_in_some_way(result)
end
...
```

Or is there something that I miss in the current implementation?

**Comment by rnienaber** [comment]
For us it is not a common use case for people to have multiple API login credentials. As such, implementing this functionality was not something we had planned to do soon.

We will add this request to the functionality list, but because it is not a primary use case it may be a while before the change is made. I will update this issue as soon as we bring the work into a sprint.

However, since this is an open source project, you are welcome to submit a pull request if this blocks your migration to V2.

**Comment by kamen-hursev** [comment]
Thanks for letting me know. We'll see how we are going to proceed with this one.
